### ISSUE TITLE
react should be peerDependancy

### ISSUE THREAD

**Issue by dpwrussell** [mapbox/react-range#12]
As it stands, react-range depends on react which can introduce a different version of React and thus to:

```
Uncaught Error: Invariant Violation: Modal.render(): A valid ReactComponent must be returned. You may have returned undefined, an array or some other invalid object.
```

It can be fixed temporarily by deleting `node_modules/react-range/node_modules/react`. I think the standard way of handling this is to make it a peer dependancy.

**Comment by damienleroux** [comment]
I made a pull request: https://github.com/mapbox/react-range/pull/20.

I'll be thankful to have it accepted please.

Thank you :)

**Comment by dasulit** [comment]
Mapbox is no longer maintaining react-range. For a current alternative, check out https://mapbox.github.io/mr-ui/#controlrange.
