### ISSUE TITLE
Error in Safari behaviour

### ISSUE THREAD

**Issue by dpwrussell** [mapbox/react-range#13]
There is a problem with this component in Safari. If you click a location on the slider and the nob jumps straight there it's ok. It is also ok if you drag and drop the slider on a specific location, but only if you do not end up with the cursor outside of the slider.

To reproduce: Select nob in Safari, move the cursor off the slider, then move sideways (the nob will move), however when you do mouseup, the `onChange` function does not fire.

**Comment by dspnorman** [comment]
I can reproduce this in Safari 9 (El Capitan) and Mobile Safari iOS 9.2.

The slider is effectively unusable on a touch device, since it's nearly impossible to ensure the drag motion ends within the slider track.

**Comment by alekseyg** [comment]
I fixed it by adding an `onInput` event handler:

```diff
@@ -7,6 +7,7 @@ var Range = React.createClass({
   displayName: 'Range',
   propTypes: {
     onChange: React.PropTypes.func,
+    onInput: React.PropTypes.func,
     onClick: React.PropTypes.func,
     onKeyDown: React.PropTypes.func,
     onMouseMove: React.PropTypes.func
@@ -15,6 +16,7 @@ var Range = React.createClass({
     return {
       type: 'range',
       onChange: function(){},
+      onInput: function(){},
       onClick: function(){},
       onKeyDown: function(){},
       onMouseMove: function(){}
@@ -25,6 +27,10 @@ var Range = React.createClass({
     if (e.buttons !== 1 && e.which !== 1) return;
     this.props.onChange(e);
   },
+  onRangeInput: function(e) {
+    this.props.onInput(e);
+    this.props.onChange(e);
+  },
   onRangeClick: function(e) {
     this.props.onClick(e);
     this.props.onChange(e);
@@ -45,6 +51,7 @@ var Range = React.createClass({
       onClick: this.onRangeClick,
       onKeyDown: this.onRangeKeyDown,
       onMouseMove: this.onRangeChange,
+      onInput: this.onRangeInput,
       onChange: function() {},
       ref: this.setRangeRef
     });
```

**Comment by dasulit** [comment]
Mapbox is no longer maintaining react-range. For a current alternative, check out https://mapbox.github.io/mr-ui/#controlrange.
